name: Lable Issues (Script Injection Example)
on:
  issues:
    types:
      - opened

jobs:
  assign-lable:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label 
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$issue_title" == *"bug"* ]]; then 
          echo "Issue is about a bug!"
          else 
          echo "Issue is not about a *"bug"
          fi 