name: Wf dispatch with input
on:
  workflow_dispatch:
    inputs:
      name: 
        description: 'Select Cluster Name'
        #default: 'AKS1'     # different values provided to wf
        type: choice
        options:
          - AKS1
          - AKS2
          - AKS3
        required: true
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      enableFeatureX:
        description: 'Enable Feature X?'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send the Command to Wf
        run: echo "Hellp ${{ github.event.inputs.name }}"
